export const texts = {
  en: {
    welcome: "Welcome to Emotions",
    welcomeregister: "Let's get",
    welcomeregisterstart: "started",
    login: "Login",
    signup: "Sign Up",
    forgotPassword: "Forgot Password?",
    enterEmail: "Enter your email",
    enterUsernameugmail: "Enter your username or gmail",
    enterPassword: "Enter your password",
    enterusername: "Enter your username",
    resetPassword: "Reset Password",
    descripcion: "Emotions is a social network designed for users to express and share their daily emotions through posts categorized by emotional states (happiness, sadness, anger, etc.)",
    heywelcome: "Hey Welcome",
    heywelcomeback: "Back",
    forgotPassword: "Forgot Password?",
    orcontinue: "or continue with",
    alreadyhave: "Already have an account!!",
    haveaccount: "Don't have an account?",
    forgot: "Forgot",
    password: "Password",
    descripciondeforgot: "Please enter your registered email address. We will send you a link to reset your password.",
  },
  es: {
    welcome: "Bienvenido a Emotions",
    welcomeregister: "Vamos a",
    welcomeregisterstart: "comenzar",
    login: "Iniciar sesión",
    signup: "Registrarse",
    forgotPassword: "¿Olvidaste tu contraseña?",
    enterEmail: "Ingresa tu correo electrónico",
    enterUsernameugmail: "Ingresa tu nombre de usuario o gmail",
    enterPassword: "Ingresa tu contraseña",
    enterusername: "Ingresa tu nombre de usuario",
    resetPassword: "Restablecer contraseña",
    descripcion: "Emotions es una red social diseñada para que los usuarios expresen y compartan sus emociones diarias a través de publicaciones categorizadas por estados emocionales (felicidad, tristeza, enojo, etc.)",
    heywelcome: "Hola, bienvenido",
    heywelcomeback: "estás de vuelta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    orcontinue: "o continúa con",
    alreadyhave: "¡Ya tienes una cuenta!",
    haveaccount: "¿No tienes una cuenta?",
    forgot: "¿Olvidaste tu",
    password: "Contraseña?",
    descripciondeforgot: "Por favor, ingresa tu dirección de correo electrónico registrada. Te enviaremos un enlace para restablecer tu contraseña.",
  }
};
