export const texts = {
  en: {
    welcome: "Welcome to Emotions",
    welcomeregister: "Let's get",
    welcomeregisterstart: "started",
    login: "Login",
    signup: "Sign Up",
    forgotPassword: "Forgot Password?",
    enterEmail: "Enter your email",
    enterUsernameugmail: "Enter your username or gmail",
    enterPassword: "Enter your password",
    enterusername: "Enter your username",
    resetPassword: "Reset Password",
    descripcion: "Emotions is a social network designed for users to express and share their daily emotions through posts categorized by emotional states (happiness, sadness, anger, etc.)",
    heywelcome: "Hey Welcome",
    heywelcomeback: "Back",
    orcontinue: "or continue with",
    alreadyhave: "Already have an account!!",
    haveaccount: "Don't have an account?",
    forgot: "Forgot",
    password: "Password",
    descripciondeforgot: "Please enter your registered email address. We will send you a link to reset your password.",
    registrationSuccess: "Registration successful",
    registrationMessage: "You have successfully registered.",
    unknownError: "Unknown error",
    invalidEmail: "The entered email is not valid.",
    emailInUse: "This email is already registered.",
    weakPassword: "The password is too weak. It must have at least 6 characters.",
    missingEmail: "You must provide an email.",
    missingPassword: "You must provide a password.",
    networkError: "Network problem. Please try again later.",
    loginSuccess: "Login successful",
    loginMessage: "You have logged in successfully!",
    passwordResetSent: "Email sent!",
    passwordResetMessage: "Check your inbox to reset your password.",
    noUserFound: "No user found with this email.",
    checkEmailFormat: "Please check the email format.",
    userDisabled: "This account has been disabled.",
    tooManyRequests: "Too many attempts. Try again later.",
    verifyEmail: "Email Verification",
    verifyEmailMessage: "We have sent a verification email. Please check your email.",
    verifyTimeout: "Timeout",
    verifyTimeoutMessage: "The email was not verified within the allowed time. Please try registering again.",
    emailVerified: "Email Verified",
    accessGranted: "Access granted. Welcome.",
    invalidApiKey: "Invalid API key. Please check your Firebase configuration.",  
  },
  es: {
    welcome: "Bienvenido a Emotions",
    welcomeregister: "Vamos a",
    welcomeregisterstart: "comenzar",
    login: "Iniciar sesión",
    signup: "Registrarse",
    forgotPassword: "¿Olvidaste tu contraseña?",
    enterEmail: "Ingresa tu correo electrónico",
    enterUsernameugmail: "Ingresa tu nombre de usuario o gmail",
    enterPassword: "Ingresa tu contraseña",
    enterusername: "Ingresa tu nombre de usuario",
    resetPassword: "Restablecer contraseña",
    descripcion: "Emotions es una red social diseñada para que los usuarios expresen y compartan sus emociones diarias a través de publicaciones categorizadas por estados emocionales (felicidad, tristeza, enojo, etc.)",
    heywelcome: "Hola, bienvenido",
    heywelcomeback: "estás de vuelta",
    orcontinue: "o continúa con",
    alreadyhave: "¡Ya tienes una cuenta!",
    haveaccount: "¿No tienes una cuenta?",
    forgot: "¿Olvidaste tu",
    password: "Contraseña?",
    descripciondeforgot: "Por favor, ingresa tu dirección de correo electrónico registrada. Te enviaremos un enlace para restablecer tu contraseña.",
    registrationSuccess: "Registro exitoso",
    registrationMessage: "Te has registrado correctamente.",
    unknownError: "Error desconocido",
    invalidEmail: "El correo electrónico ingresado no es válido.",
    emailInUse: "Este correo electrónico ya está registrado.",
    weakPassword: "La contraseña es demasiado débil. Debe tener al menos 6 caracteres.",
    missingEmail: "Debes proporcionar un correo electrónico.",
    missingPassword: "Debes proporcionar una contraseña.",
    networkError: "Problema de red. Intenta nuevamente más tarde.",
    loginSuccess: "Inicio de sesión exitoso",
    loginMessage: "¡Has iniciado sesión correctamente!",
    passwordResetSent: "¡Correo enviado!",
    passwordResetMessage: "Revisa tu bandeja de entrada para restablecer tu contraseña.",
    noUserFound: "No se encontró ningún usuario con este correo.",
    checkEmailFormat: "Por favor, verifica el formato del correo electrónico.",
    userDisabled: "Esta cuenta ha sido deshabilitada.",
    tooManyRequests: "Demasiados intentos. Intenta nuevamente más tarde.",
    verifyEmail: "Verificación de correo",
    verifyEmailMessage: "Hemos enviado un correo de verificación. Por favor, verifica tu email.",
    verifyTimeout: "Tiempo agotado",
    verifyTimeoutMessage: "No se verificó el correo en el tiempo permitido. Intenta registrarte de nuevo.",
    emailVerified: "Correo verificado",
    accessGranted: "Acceso concedido. Bienvenido.",
    invalidApiKey: "Clave de API inválida. Por favor, verifica tu configuración de Firebase."  
  }
} 